// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// dim_names.cpp
list union_dim_names(list x, list y, bool only_x);
extern "C" SEXP _rearray_union_dim_names(SEXP x, SEXP y, SEXP only_x) {
  BEGIN_CPP11
    return cpp11::as_sexp(union_dim_names(cpp11::as_cpp<cpp11::decay_t<list>>(x), cpp11::as_cpp<cpp11::decay_t<list>>(y), cpp11::as_cpp<cpp11::decay_t<bool>>(only_x)));
  END_CPP11
}
// dim_names.cpp
strings cpp_unique(strings xs);
extern "C" SEXP _rearray_cpp_unique(SEXP xs) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_unique(cpp11::as_cpp<cpp11::decay_t<strings>>(xs)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_rearray_cpp_unique",      (DL_FUNC) &_rearray_cpp_unique,      1},
    {"_rearray_union_dim_names", (DL_FUNC) &_rearray_union_dim_names, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_rearray(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
