// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// broadcast.cpp
list_of<integers> match_dim_names(list new_dim_names, list old_dim_names);
extern "C" SEXP _rearray_match_dim_names(SEXP new_dim_names, SEXP old_dim_names) {
  BEGIN_CPP11
    return cpp11::as_sexp(match_dim_names(cpp11::as_cpp<cpp11::decay_t<list>>(new_dim_names), cpp11::as_cpp<cpp11::decay_t<list>>(old_dim_names)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_rearray_match_dim_names", (DL_FUNC) &_rearray_match_dim_names, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_rearray(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
