# Generated by cpp11: do not edit by hand

union_dim_names <- function(x, y, only_x) {
  .Call(`_rearray_union_dim_names`, x, y, only_x)
}

cpp_unique <- function(xs) {
  .Call(`_rearray_cpp_unique`, xs)
}
